myproject/checklist/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.checklist_filter_list, name='filter'),
    url(r'^(?P<pk>\d+)/$', views.ChecklistDetailView.as_view(), name='detail'),
    url(r'^create/$', views.ChecklistCreateView.as_view(), name='create'),
    url(r'^edit/(?P<pk>\d+)/$', views.ChecklistUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.ChecklistDeleteView.as_view(), name='delete'),
]

myproject/myproject/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^checklist/', include('checklist.urls', app_name='checklist', namespace='checklist')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'^home/', views.index),
    url(r'^contact/', views.contact),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

myproject/checklist/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Refers to the general category of a "to-do" item
class Category(models.Model):
    type = models.CharField(max_length=255)

    def __str__(self):
        return self.type


# Refers to a "to-do" item
class Checklist(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    category = models.ForeignKey(Category)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    # Returns detail view link
    def get_absolute_url(self):
        return reverse('checklist:detail', kwargs={'pk': self.pk})

myproject/checklist/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from .models import Checklist


class ChecklistForm(ModelForm):
    class Meta:
        model = Checklist
        fields = ('title', 'start_date', 'end_date', 'description', 'category', 'completed')

    #Validation error to check if the end date is less than the start date, if so display message
    def clean(self):
        cleaned_data = super(ChecklistForm, self).clean()

        start_date_clean = cleaned_data.get('start_date')
        end_date_clean = cleaned_data.get('end_date')

        if start_date_clean and end_date_clean:
            if start_date_clean > end_date_clean:
                self.add_error(None, ValidationError('End Date must be greater than Start Date'))

myproject/checklist/views.py
from django.db.models import F
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView

from .filters import ChecklistFilter
from .forms import ChecklistForm
from .models import Checklist

#Detail view summary for individual checklist item
def checklist_detail(request, pk):
    checklist = get_object_or_404(Checklist, pk=pk)
    return render(request, 'checklist/checklist_detail.html', {'checklist': checklist})

#Generic - Detail view summary for individual checklist item
class ChecklistDetailView(DetailView):
    model = Checklist

#Generic - Create view for new checklist item
class ChecklistCreateView(CreateView):
    model = Checklist
    form_class = ChecklistForm

#Generic - Update view for existing checklist item
class ChecklistUpdateView(UpdateView):
    model = Checklist
    form_class = ChecklistForm

#Generic - Delete view for existing checklist item
class ChecklistDeleteView(DeleteView):
    model = Checklist
    success_url = '/checklist/'

#Filter view for all checklist items (Main Display Page)
def checklist_filter_list(request):
    #Order by completed date, then end date, then start date
    checklist_queryset = Checklist.objects.all().order_by('completed', F('end_date').asc(nulls_last=True), F('start_date').asc(nulls_last=True))

    f = ChecklistFilter(request.GET, queryset=checklist_queryset)
    return render(request, 'checklist/checklist_filter.html', {'filter': f})

myproject/myproject/views.py
from django.shortcuts import render

# For home page
def index(request):
    return render(request, 'index.html')

# For home page
def home(request):
    return render(request, 'index.html')

# For contact page
def contact(request):
    return render(request, 'contact.html')

myproject/checklist/templates/checklist/checklist_confirm_delete.html
{% extends 'layout.html' %}
{% load static from staticfiles %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form_style.css' %}" />
{% endblock %}

{% block content %}

<div class="container form-page">

	<!-- Page Header -->
	<div class='page-header'>
		<h1 class="hide-mobile">Delete <span class="edit-item">{{ checklist.title }}</span>?</h1>
		<h1 class="show-mobile">Delete? </h1>
	</div>

	<!-- Delete Form -->
<form method='POST'>
	<div class="form-input">
		{% csrf_token %}
		<div class="fieldWrapper row">
			<div class="col-xs-12 col-sm-3"><strong>Title:</strong></div>
			<div class="col-xs-12 col-sm-9">{{ checklist.title }}</div>
		</div>
		<div class="fieldWrapper row">
			<div class="col-xs-12 col-sm-3"><strong>Start Date:</strong></div>
			<div class="col-xs-12 col-sm-9">{{ checklist.start_date }}</div>
		</div>
		<div class="fieldWrapper row">
			<div class="col-xs-12 col-sm-3"><strong>Start Date:</strong></div>
			<div class="col-xs-12 col-sm-9">{{ checklist.end_date }}</div>
		</div>
		<div class="fieldWrapper row">
			<div class="col-xs-12 col-sm-3"><strong>Description:</strong></div>
			<div class="col-xs-12 col-sm-9">{{ checklist.description }}</div>
		</div>
		{% if checklist.category %}
		<div class="fieldWrapper row">
			<div class="col-xs-12 col-sm-3"><strong>Category:</strong></div>
			<div class="col-xs-12 col-sm-9">{{ checklist.category }}</div>
		</div>
		{% endif %}
		<div class="fieldWrapper row">
			<div class="col-xs-12 col-sm-3"><strong>Completed:</strong></div>
			<div class="col-xs-12 col-sm-9">{% if checklist.completed %}Yes{% else %}No{% endif %}</div>
		</div>
	</div>

	<!-- Delete and Cancel buttons -->
	<div class='text-center'>
		<div class='btn-grp'>
			<input type="submit" class="btn btn-danger btn-add" value="Delete">
			<div class="btn btn-warning"><a class="btn-add" href="\checklist">Cancel</a></div>
		</div>
	</div>
</form>
</div>
{% endblock %}

myproject/checklist/templates/checklist/checklist_detail.html
{% extends 'layout.html' %}
{% load static from staticfiles %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form_style.css' %}" />
{% endblock %}

{% block content %}

<div class="container form-page">

    <!-- Page Header -->
	<div class='page-header'>
		<h1 class="hide-mobile"><span class="edit-item">{{ checklist.title }}</span></h1>
		<h1 class="show-mobile">Detail For:</h1>
	</div>

    <!-- Detail Form -->
    <div class="form-input">
        <div class="fieldWrapper row">
            <div class="col-xs-12 col-sm-3"><strong>Title:</strong></div>
            <div class="col-xs-12 col-sm-9">{{ checklist.title }}</div>
        </div>
        <div class="fieldWrapper row">
            <div class="col-xs-12 col-sm-3"><strong>Start Date:</strong></div>
            {% if checklist.start_date %}
                <div class="col-xs-12 col-sm-9">{{ checklist.start_date|date:'F j, Y' }}</div>
            {% else %}
                <div class="col-xs-12 col-sm-9">{{ checklist.start_date }}</div>
            {% endif %}
        </div>
        <div class="fieldWrapper row">
            <div class="col-xs-12 col-sm-3"><strong>End Date:</strong></div>
            {% if checklist.end_date %}
                <div class="col-xs-12 col-sm-9">{{ checklist.end_date|date:'F j, Y' }}</div>
            {% else %}
                <div class="col-xs-12 col-sm-9">{{ checklist.end_date }}</div>
            {% endif %}
        </div>
        <div class="fieldWrapper row">
            <div class="col-xs-12 col-sm-3"><strong>Description:</strong></div>
            <div class="col-xs-12 col-sm-9">{{ checklist.description }}</div>
        </div>
        {% if checklist.category %}
        <div class="fieldWrapper row">
            <div class="col-xs-12 col-sm-3"><strong>Category:</strong></div>
            <div class="col-xs-12 col-sm-9">{{ checklist.category }}</div>
        </div>
        {% endif %}
        <div class="fieldWrapper row">
            <div class="col-xs-12 col-sm-3"><strong>Completed:</strong></div>
            <div class="col-xs-12 col-sm-9">{% if checklist.completed %}Yes{% else %}No{% endif %}</div>
        </div>
	</div>

    <!-- Edit or Cancel buttons -->
	<div class='text-center'>
		<div class='btn-grp'>
			<div class="btn btn-success"><a class="btn-add" href="{% url 'checklist:update' pk=checklist.pk %}">Edit</a></div>
			<div class="btn btn-warning"><a class="btn-add" href="\checklist">Cancel</a></div>
		</div>
	</div>
</div>
{% endblock %}

myproject/checklist/templates/checklist/checklist_filter.html
{% extends 'layout.html' %}
{% load static from staticfiles %}
{% load checklist_tags %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form_style.css' %}" />
{% endblock %}

{% block content %}

<div class="container form-page">

	<!-- Page Header -->
	<div class='page-header'>
  		<div class='btn-toolbar pull-right'>
    		<div class='btn-group'>
      			<div class='btn btn-success'><a href="{% url 'checklist:create' %}" class="btn-add">Add New Item</a></div>
    		</div>
  		</div>
  		<h1 class="hide-mobile list-title">To Do List:</h1>
		<h1 class="show-mobile list-title">To Do:</h1>
	</div>

	<!-- Filter Form -->
    <div class="filter-section list-section">
        <form action="" method="get">
            {% for field in filter.form %}
                    <div class="filterWrapper row">
                        {{ field.label_tag }}
                        {{ field|addclass:'input-field' }}
                    </div>
            {% endfor %}
            <div class="text-center">
                <input type="submit" class="btn btn-primary btn-add" value="Filter" />
            </div>
        </form>
    </div>

	<!-- Filtered Records -->
<div class="list-section">
	<div class="row">
			<div class="col-xs-6 col-sm-5 table-headers">Title</div>
			<div class="hidden-xs col-sm-2 table-headers">Start Date</div>
			<div class="col-xs-3 col-sm-2 table-headers">End Date</div>
            <div class="hidden-xs col-sm-2 table-headers">Category</div>
			<div class="col-xs-3 col-sm-1 table-headers">Completed</div>
	</div>
		{% for item in filter.qs %}
			<div class="row">
				<div class="col-xs-6 col-sm-5 no-padding"><a href="\checklist\edit\{{ item.id }}\">{{ item.title }}</a></div>
				<div class="hidden-xs col-sm-2 no-padding">
					{% if item.start_date %}
						{{ item.start_date|date:"m/d/Y" }}
					{% else %}
						{{ item.start_date }}
					{% endif %}
				</div>
				<div class="col-xs-3 col-sm-2 no-padding">
					{% if item.end_date %}
						{{ item.end_date|date:"m/d/Y" }}
					{% else %}
						{{ item.end_date }}
					{% endif %}
				</div>
                <div class="hidden-xs col-sm-2 no-padding">{{ item.category }}</div>
				<div class="col-xs-3 col-sm-1 no-padding">{% if item.completed %}Yes{% else %}No{% endif %}</div>

			</div>
		{% endfor %}
</div>

</div>
{% endblock %}

{% block script %}
<script>
	/* Generic column sizes for label fields */
	jQuery("label").addClass('col-xs-12 col-sm-3');
	/* Generic column sizes for input fields */
	jQuery('.input-field').addClass('col-xs-12 col-sm-9');

	/* Remove generic column and label sizes for completed field  */
	jQuery('label[for^="id_completed"]').removeClass();
	jQuery('input[id^="id_completed"]').removeClass();
	jQuery('label[for^="id_completed"]:first').addClass('col-xs-12 col-sm-3');
	jQuery('.filterWrapper li').addClass('col-xs-4 col-sm-2');

	/* Remove generic column and label sizes for date fields  */
    jQuery('#id_start_date_1').removeClass('col-xs-12 col-sm-9').addClass('col-xs-6 col-sm-3 col-xs-offset-1 col-sm-offset-1');
	jQuery('#id_end_date_1').removeClass('col-xs-12 col-sm-9').addClass('col-xs-6 col-sm-3 col-xs-offset-1 col-sm-offset-1');
	jQuery('#id_start_date_0').removeClass('col-xs-12 col-sm-9').addClass('col-xs-5 col-sm-3');
	jQuery('#id_end_date_0').removeClass('col-xs-12 col-sm-9').addClass('col-xs-5 col-sm-3');

	/* Add datepicker  */
    jQuery('#id_start_date_0').addClass('datepicker');
	jQuery('#id_end_date_0').addClass('datepicker');

	/* Set datepicker format */
	$(document).ready(function () {
        $('.datepicker').datepicker({
            format: "mm/dd/yyyy"
        });
    });
</script>
{% endblock %}

myproject/checklist/templates/checklist/checklist_form.html
{% extends 'layout.html' %}
{% load static from staticfiles %}
{% load checklist_tags %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form_style.css' %}" />
{% endblock %}

{% block content %}
<div class="container form-page">

	<!-- Page Header -->
	<div class='page-header'>
		<h1 class="hide-mobile">{% if not form.instance.pk %}Create New: {% else %}Edit <span class="edit-item">{{ form.instance.title }}</span>{% endif %}</h1>
		<h1 class="show-mobile">{% if not form.instance.pk %}Create New: {% else %}Edit: {% endif %}</h1>
	</div>

	<!-- Form fields -->
<form method='POST'>
	<div class="form-input">
		{% csrf_token %}
			{{ form.non_field_errors }}
			{% for field in form %}
				<div class="fieldWrapper row">
					{{ field.errors }}
					{{ field.label_tag }}
					{{ field|addclass:'input-field' }}
					{% if field.help_text %}
						<p class="help">{{ field.help_text|safe }}</p>
					{% endif %}
				</div>
			{% endfor %}
	</div>

	<!-- Save Cancel and Delete buttons -->
	<div class='text-center'>
    	<div class='btn-grp'>
			<input type="submit" class="btn btn-success btn-add" value="Save">
			<div class="btn btn-warning"><a class="btn-add" href="\checklist">Cancel</a></div>
			{% if form.instance.pk %}<a class="btn btn-danger btn-add" href="{% url 'checklist:delete' pk=checklist.pk %}">Delete</a>{% endif %}
		</div>
	</div>
</form>
</div>
{% endblock %}

{% block script %}
<script>
	/* Add datepicker to date fields */
	jQuery('#id_start_date').addClass('datepicker');
	jQuery('#id_end_date').addClass('datepicker');

	/* Generic column sizes for label fields */
	jQuery("label").addClass('col-xs-12 col-sm-3');
	/* Generic column sizes for input fields */
	jQuery('.input-field').addClass('col-xs-12 col-sm-9');

	/* Remove generic column and label sizes for completed field  */
	jQuery('#id_completed').removeClass().addClass('col-sm-9').css("width","auto");
	jQuery('label[for="id_completed"]').removeClass().addClass('col-sm-3');

	/* Set datepicker format */
	$(document).ready(function () {
        $('.datepicker').datepicker({
            format: "mm/dd/yyyy"
        });
    });
</script>
{% endblock %}

myproject/templates/contact.html
{% extends "layout.html" %}

{% block content %}
    <div class="container">

    <!-- Page Header -->
    <div class='page-header'>
  		<h1>Contact Us</h1>
	</div>

        <!-- Contact Information -->
        <div class="contact col-sm-6 col-sm-offset-4">
            <p><strong>For any inquiries about this site, please contact:</strong></p>
            <br><br />
            <p>One Checklist Way<p>
            <p>Louisville, KY 33333-3333</p>
            <p>P:333.333.3333</p>
            <br><br />
            <strong>Support:</strong>
            <a href="mailto:Support@example.com">Support@example.com</a>
        </div>

    </div>
{% endblock content %}

myproject/templates/index.html
{% extends "layout.html" %}

{% block content %}
<div class="parent-container">

    <div class="container">

        <!-- Main graphic on home page -->
        <div class="main-logo">
            <p class="main-color-1 text-left">Check<span class="main-color-2">list&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
            <p class="main-color-1 text-right">&nbsp;&nbsp;&nbsp;&nbsp;Yourself</p>
        </div>
        <p class="main-text text-center">A new way to organize your to-do list.</p>

    </div>

</div>
{% endblock content %}

myproject/templates/layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Your Checklist</title>

    <!-- Insert Style Sheet Here-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datepicker3.min.css' %}" />
    <!-- <link rel="stylesheet" type="text/plain" href="{% static 'css/bootstrap-datepicker3.min.css.map' %}" /> -->
    {% block css %}{% endblock %}

    <!-- Insert Google Fonts Here -->
    <link href="https://fonts.googleapis.com/css?family=Bitter:400,700" rel="stylesheet">
</head>

<body>
    <!-- Header -->
    <section class="header">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <p class="navbar-text nav-header-text-xs"><strong>Check<span class="nav-color-2">list</span> Yourself</strong></p>
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="\home">Home</a></li>
                        <li><a href="\checklist">Get Started!</a></li>
                        <li><a href="\contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>

    </section>
    <!-- /Header -->
    {% block content %}{% endblock %}
    <!-- Footer -->
    <footer class="footer">
         <p>&copy; {% now "Y" %} - Checklist Yourself</p>
    </footer>
    <!-- /Footer -->

    <!-- Insert JavaScript Here -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap-datepicker.min.js' %}" type="text/javascript"></script>
    {% block script %}{% endblock %}

</body>
</html>